CC=gcc 
CFLAGS = -g

all: twos bitwise

twos: Lesson2_Twos_Complement.c
	$(CC) -c Lesson2_Twos_Complement.c $(CFLAGS)

bitwise: Lesson1_Bitwise_Print.c 
	$(CC) -c Lesson1_Bitwise_Print.c $(CFLAGS)

clean:
	rm -f *.o 